name: Build APK with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Build Docker Image
        run: |
          git clone https://github.com/kivy/buildozer
          cd buildozer
          docker build -t buildozer .

      - name: Run Buildozer in Docker
        run: |
          docker run --rm -v $PWD:/home/user/hostcwd buildozer buildozer android debug
