name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sh

      - name: Build Docker Image for Buildozer
        run: |
          git clone https://github.com/kivy/buildozer.git
          cd buildozer
          docker build -t buildozer .

      - name: Run Buildozer to Build APK
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd buildozer buildozer -v android debug
