name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          pip install buildozer cython

     - name: Set up Android SDK
  run: |
    mkdir -p $ANDROID_HOME/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROID_HOME/cmdline-tools
    mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

- name: Accept SDK Licenses
  run: |
    yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

- name: Install Android Tools
  run: |
    $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-31" "cmdline-tools;latest"


      - name: Build APK
        run: buildozer android debug
